% Define the message to be displayed
message = {['Antes de empezar a utilizar este proyecto, lee las' ...
    'indicaciones dadas en el readme del repositorio y en la presentación' ...
    ' \Miscellaneous\Subject introduction and description' ...
    ' for teachers_EN.pptx.'];...
    '';...
    ['Before you start using this project, please read the instructions' ...
    ' given in the repository readme and in the presentation' ...
    ' \Miscellaneous\Subject introduction and description' ...
    ' for teachers_EN.pptx.']
    '';...
    ['Proiektu hau erabiltzen hasi baino lehen,' ...
    ' irakurri repositorioko readme fitxategia edo' ...
    ' \Miscellaneous\Subject introduction and description' ...
    ' for teachers_EN.pptx.']};


% Create a message box with the specified message
msgbox(message, 'Start up', 'modal');